### ISSUE TITLE
Move "RF Power" button to main UI

### ISSUE THREAD

**Issue by elumspe** [yukilabo/705RemoteSupport#1]
Would you consider moving the "RF Power" selection to the main UI? 

Alternatively, add multiple buttons with predefined RF power values?

**Comment by yukilabo** [comment]
The "RF Power" is placed in the options menu because I think it is rarely changed.
Can you tell me more about why it needs to be placed in the main UI?

**Comment by elumspe** [comment]
From my perspective:

1. When doing QRP, I usually change the RF output to push the limits of the minimum power. So it would help such operations. 
2. Adding "RF power" to the main UI may not benefit all the users, but it won't hurt any current user experience neither.
3. I think putting "RF power" on the main UI is more intuitive than under the second layer of the options menu.
4. I understand you may reserve the main UI space to add more features to the APP. And please consider holding a box for the "RF Power" option :)

BTW, thank you for your wonderful work. This is a great App with lots of potentials.
